set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets CLK]
set_property -dict {PACKAGE_PIN T10 IOSTANDARD LVCMOS33} [get_ports {SEG[0]}]
set_property -dict {PACKAGE_PIN R10 IOSTANDARD LVCMOS33} [get_ports {SEG[1]}]
set_property -dict {PACKAGE_PIN K16 IOSTANDARD LVCMOS33} [get_ports {SEG[2]}]
set_property -dict {PACKAGE_PIN K13 IOSTANDARD LVCMOS33} [get_ports {SEG[3]}]
set_property -dict {PACKAGE_PIN P15 IOSTANDARD LVCMOS33} [get_ports {SEG[4]}]
set_property -dict {PACKAGE_PIN T11 IOSTANDARD LVCMOS33} [get_ports {SEG[5]}]
set_property -dict {PACKAGE_PIN L18 IOSTANDARD LVCMOS33} [get_ports {SEG[6]}]
set_property -dict {PACKAGE_PIN H15 IOSTANDARD LVCMOS33} [get_ports DP]
set_property -dict {PACKAGE_PIN J17 IOSTANDARD LVCMOS33} [get_ports {AN[0]}]
set_property -dict {PACKAGE_PIN J18 IOSTANDARD LVCMOS33} [get_ports {AN[1]}]
set_property -dict {PACKAGE_PIN T9 IOSTANDARD LVCMOS33} [get_ports {AN[2]}]
set_property -dict {PACKAGE_PIN J14 IOSTANDARD LVCMOS33} [get_ports {AN[3]}]
set_property -dict {PACKAGE_PIN P14 IOSTANDARD LVCMOS33} [get_ports {AN[4]}]
set_property -dict {PACKAGE_PIN T14 IOSTANDARD LVCMOS33} [get_ports {AN[5]}]
set_property -dict {PACKAGE_PIN K2 IOSTANDARD LVCMOS33} [get_ports {AN[6]}]
set_property -dict {PACKAGE_PIN U13 IOSTANDARD LVCMOS33} [get_ports {AN[7]}]
set_property SLEW SLOW [get_ports DP]
set_property SLEW SLOW [get_ports {SEG[6]}]
set_property SLEW SLOW [get_ports {SEG[5]}]
set_property SLEW SLOW [get_ports {SEG[4]}]
set_property SLEW SLOW [get_ports {SEG[3]}]
set_property SLEW SLOW [get_ports {SEG[2]}]
set_property SLEW SLOW [get_ports {SEG[1]}]
set_property SLEW SLOW [get_ports {SEG[0]}]
set_property SLEW SLOW [get_ports {AN[7]}]
set_property SLEW SLOW [get_ports {AN[6]}]
set_property SLEW SLOW [get_ports {AN[5]}]
set_property SLEW SLOW [get_ports {AN[4]}]
set_property SLEW SLOW [get_ports {AN[3]}]
set_property SLEW SLOW [get_ports {AN[2]}]
set_property SLEW SLOW [get_ports {AN[1]}]
set_property SLEW SLOW [get_ports {AN[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[0]}]
set_property SLEW SLOW [get_ports {LED[7]}]
set_property SLEW SLOW [get_ports {LED[6]}]
set_property SLEW SLOW [get_ports {LED[5]}]
set_property SLEW SLOW [get_ports {LED[4]}]
set_property SLEW SLOW [get_ports {LED[3]}]
set_property SLEW SLOW [get_ports {LED[2]}]
set_property SLEW SLOW [get_ports {LED[1]}]
set_property SLEW SLOW [get_ports {LED[0]}]
set_property PACKAGE_PIN V11 [get_ports {LED[7]}]
set_property PACKAGE_PIN V12 [get_ports {LED[6]}]
set_property PACKAGE_PIN V14 [get_ports {LED[5]}]
set_property PACKAGE_PIN V15 [get_ports {LED[4]}]
set_property PACKAGE_PIN T16 [get_ports {LED[3]}]
set_property PACKAGE_PIN U14 [get_ports {LED[2]}]
set_property PACKAGE_PIN T15 [get_ports {LED[1]}]
set_property PACKAGE_PIN V16 [get_ports {LED[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports speaker]
set_property PACKAGE_PIN A11 [get_ports speaker]
set_property PACKAGE_PIN F4 [get_ports ps2_clk]
set_property PACKAGE_PIN E3 [get_ports CLK]
set_property IOSTANDARD LVCMOS33 [get_ports CLK]
set_property IOSTANDARD LVCMOS33 [get_ports ps2_clk]
set_property PULLUP true [get_ports ps2_clk]
set_property PACKAGE_PIN B2 [get_ports ps2_data]
set_property PACKAGE_PIN V10 [get_ports r1]
set_property PACKAGE_PIN U11 [get_ports r2]
set_property PACKAGE_PIN U12 [get_ports r3]
set_property PACKAGE_PIN H6 [get_ports r4]
set_property IOSTANDARD LVCMOS33 [get_ports ps2_data]
set_property IOSTANDARD LVCMOS33 [get_ports r1]
set_property IOSTANDARD LVCMOS33 [get_ports r2]
set_property IOSTANDARD LVCMOS33 [get_ports r3]
set_property IOSTANDARD LVCMOS33 [get_ports r4]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property PULLUP true [get_ports ps2_data]
set_property PACKAGE_PIN N17 [get_ports rst]
